### ISSUE TITLE
What does alpha[idx]  mean in focal loss?

### ISSUE THREAD

**Issue by JunMa11** [Hsuxu/Loss_ToolBox-PyTorch#8]
Dear @Hsuxu ,

I'm sorry to bother you again. 

I do not understand the following `alpha[idx]`, and I get a weired memory problem when using focal loss for 3D multi-class segmentation task.
> RuntimeError: CUDA out of memory. Tried to allocate 19600.00 GiB.

`idx = target.cpu().long()`
https://github.com/Hsuxu/Loss_ToolBox-PyTorch/blob/7ba9e6487f23fb5ea3c2e17ca74ae10a4cccd1c1/FocalLoss/FocalLoss.py#L76

**Could you please give some explanation about `alpha = alpha[idx]`?**

**Comment by ksarma** [comment]
I'm also having a similar issue, currently working on figuring it out

**Comment by Hsuxu** [comment]
Sorry, it's a mistake. It should not be an inplace operation.
Change to 
```
alpha_class = alpha[idx]
loss = -1 * alpha_class * torch.pow((1 - pt), gamma) * logpt
```
Please test again.

**Comment by ksarma** [comment]
I actually realized that I may have been having a different issue, as I was getting my memory error on the second line (loss = ...)

I wonder if it might be necessary to squeeze alpha_class before using it? Otherwise I believe it may try to produce a matrix multiplication result that is a square matrix of the length of alpha_class (which is quite large).

**Comment by JunMa11** [comment]
@Hsuxu Thanks for your reply.
@ksarma , Yes, this is what I do and it works.
